services:
  api:
    build: ./api
    container_name: api
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - PROFILE_ACTIVE=${PROFILE_ACTIVE}
      - WEB_URL=${WEB_URL}
      - API_URL=${API_URL}
      - POSTGRES_HOST=database
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USERNAME=${MAILER_USERNAME}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_FROM=${MAILER_FROM}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_BLOG_WEB_CLIENT_ID=${KEYCLOAK_BLOG_WEB_CLIENT_ID}
      - KEYCLOAK_BLOG_API_CLIENT_ID=${KEYCLOAK_BLOG_API_CLIENT_ID}
      - KEYCLOAK_BLOG_API_CLIENT_SECRET=${KEYCLOAK_BLOG_API_CLIENT_SECRET}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
    depends_on:
      - database
    networks:
      - local-network

  web:
    build:
      context: ./web
      args:
        - WEB_URL=${WEB_URL}
        - API_URL=${API_URL}
        - API_URL_SERVER=${API_URL_SERVER}
        - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
        - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - KEYCLOAK_REALM=${KEYCLOAK_REALM}
        - KEYCLOAK_BLOG_WEB_CLIENT_ID=${KEYCLOAK_BLOG_WEB_CLIENT_ID}
        - KEYCLOAK_BLOG_WEB_CLIENT_SECRET=${KEYCLOAK_BLOG_WEB_CLIENT_SECRET}
    container_name: web
    expose:
      - "3000"
    ports:
    - "3000:3000"
    networks:
      - local-network

  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8080"
    ports:
      - "8085:8080"
    depends_on:
      - database
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  pgdata:
