events {}

http {

  server {
    listen 443 ssl;
    server_name yourdomain.com;

    ssl_certificate     /certs/yourdomain.com.pem;
    ssl_certificate_key /certs/yourdomain.com-key.pem;

    # FRONTEND
    location / {
      proxy_pass http://web:3000; # Production

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # BACKEND
    location /api/ {
      proxy_pass http://api:8080/; # Production

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port 443;
    }

    # OAUTH2 CALLBACK
    location /login/oauth2/ {
      proxy_pass http://api:8080/login/oauth2/; # Production

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }

    # ADMIN
    location /pgadmin/ {
        proxy_pass http://admin:80/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Script-Name /pgadmin;
        proxy_redirect off;
    }
  }

}
