name=blog
parent=base
import=common/keycloak
locales=pt-BR
homeUrl=http://localhost:3000
contactUrl=http://localhost:3000/contact
githubUrl=https://github.com/cirobtorres/blog
styles=css/login.css css/tailwind.css
