spring:
  application:
    name: api

  profiles:
    active: ${PROFILE_ACTIVE:production}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      data-source-properties:
        prepareThreshold: 0

  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read:user
              - user:email

  mail:
    host: ${MAILER_HOST}
    port: ${MAILER_PORT} # STARTTLS = 587 (usually)
    username: ${MAILER_USERNAME}
    password: ${MAILER_PASSWORD} # API Key
    properties:
      mail:
        smtp:
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000

# ApiApplicationProperties
api-properties:
  frontend:
    url: ${WEB_URL}
  application:
    privateKey: ${RSA_PRIVATE_CONTENT}
    publicKey: ${RSA_PUBLIC_CONTENT}
    mailerFrom: ${MAILER_FROM}
    mediaUpServName: ${CLOUDINARY_CLOUD_NAME}
    mediaUpServKey: ${CLOUDINARY_API_KEY}
    mediaUpServSecret: ${CLOUDINARY_API_SECRET}
  jwt:
    issuer: ${API_URL}
    expAccToken: 900000 # 900000 = 15 min; 3600000 = 60 min
    expRefToken: 604800000 # 7 days
    accTokenPath: "/"
    refTokenPath: "/"

# Logs
logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

# APP
server:
  error:
    whitelabel:
      enabled: false

# Actuator
management:
  server:
    port: 9090


# ...

--- # DEVELOPMENT
spring:
  config:
    activate:
      on-profile: development

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # ddl-auto: none            # DEFAULT. No DDL operations (fully manual control of DB schema)
  # ddl-auto: validate        # Validates the existing schema. If mismatched, app won't start
  # ddl-auto: update          # Updates incrementally for classes with @Entity annotation, never to remove columns/drop tables
  # ddl-auto: create          # The database schema is dropped and completely re-created on every application startup
  # ddl-auto: create-only     # The database schema is generated, but existing tables are not dropped first
  # ddl-auto: create-drop     # The schema is created on startup and dropped when the application stops
  # ddl-auto: drop            # Only the database schema is dropped

  mail:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

api-properties:
  application:
    production: false

# Colorful terminal (not every terminal supports it)
output:
  ansi:
    enabled: always

# Logs (detailed)
logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    org.springframework.boot.autoconfigure.jdbc: debug
  file:
    name: api.log

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"


# ...

--- # PRODUCTION
spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  # ddl-auto: none            # DEFAULT. No DDL operations (fully manual control of DB schema)
  # ddl-auto: validate        # Validates the existing schema. If mismatched, app won't start
  # ddl-auto: update          # Updates incrementally for classes with @Entity annotation, never to remove columns/drop tables
  # ddl-auto: create          # The database schema is dropped and completely re-created on every application startup
  # ddl-auto: create-only     # The database schema is generated, but existing tables are not dropped first
  # ddl-auto: create-drop     # The schema is created on startup and dropped when the application stops
  # ddl-auto: drop            # Only the database schema is dropped

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true # TLS only
          ssl:
            trust: "*"

# ApiApplicationProperties
api-properties:
  application:
    production: true

# Logs
logging:
  level:
    root: warn
    org.springframework.web: warn
    org.hibernate.SQL: warn # query
    org.hibernate.orm.jdbc.bind: warn # parameters (?)
    org.hibernate.type.descriptor.sql: warn

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info" # Hide sensitive data

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework
# ...
