import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";
import NightThemeSwitcher from "../components/NightThemeSwitch";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userTheme = cookies().get("theme")?.value || "";

  return (
    <html lang="pt">
      <body
        className={`${inter.className} ${userTheme} min-h-svh flex flex-col justify-center items-center bg-main dark:bg-dark-main`}
      >
        <header className="w-full h-20 bg-header dark:bg-dark-header">
          <div className="h-full flex items-center max-w-webpage mx-auto">
            <NightThemeSwitcher theme={userTheme} />
          </div>
        </header>
        <main className="w-full h-full flex-1 flex flex-col">{children}</main>
        <footer className="w-full h-40 bg-footer dark:bg-dark-footer"></footer>
      </body>
    </html>
  );
}
