import type { Metadata } from "next";
import { ThemeProvider } from "../contexts/themeContext";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <ThemeProvider>{children}</ThemeProvider>
    </html>
  );
}
