import type { Metadata } from "next";
import BodyComponent from "../../components/Body";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicationsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <BodyComponent>{children}</BodyComponent>;
}
