import type { Metadata } from "next";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative w-full h-full flex border-b border-base-200 dark:border-dark-base-border">
      <NavBar />
      <div className="w-full h-full max-w-webpage mx-auto bg-base-100 dark:bg-dark-base-100">
        {children}
      </div>
    </div>
  );
}
